--- #YAML:1.0
name:                Heap-Simple-Perl
version:             0.14
abstract:            ~
license:             ~
author:              
    - Ton Hospel <Heap-Simple@ton.iguana.be>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Heap::Simple:                  0.09
    Test::More:                    0.11
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
